services:
  db:
    image: mysql
    command: [
      '--sql-mode=NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION',
      '--default-authentication-plugin=mysql_native_password',
      '--log_output=FILE',
      '--slow_query_log=on',
      '--long_query_time=1',
      '--log_bin_trust_function_creators=on',
      '--group_concat_max_len=4294967295',
    ]
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "expense-tracker"
      TZ: "UTC"
    volumes:
      - db_data:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "3306:3306"
    restart: unless-stopped
volumes:
  db_data: